import unittest
from meu_grafo_lista_adj import *
from bibgrafo.grafo_errors import *
from bibgrafo.aresta import Aresta


class TestGrafo(unittest.TestCase):

    def setUp(self):
        # Grafo da Paraíba
        self.g_p = MeuGrafo()
        self.g_p.adiciona_vertice("J")
        self.g_p.adiciona_vertice("C")
        self.g_p.adiciona_vertice("E")
        self.g_p.adiciona_vertice("P")
        self.g_p.adiciona_vertice("M")
        self.g_p.adiciona_vertice("T")
        self.g_p.adiciona_vertice("Z")
        self.g_p.adiciona_aresta('a1', 'J', 'C')
        self.g_p.adiciona_aresta('a2', 'C', 'E')
        self.g_p.adiciona_aresta('a3', 'C', 'E')
        self.g_p.adiciona_aresta('a4', 'P', 'C')
        self.g_p.adiciona_aresta('a5', 'P', 'C')
        self.g_p.adiciona_aresta('a6', 'T', 'C')
        self.g_p.adiciona_aresta('a7', 'M', 'C')
        self.g_p.adiciona_aresta('a8', 'M', 'T')
        self.g_p.adiciona_aresta('a9', 'T', 'Z')

        # Clone do Grafo da Paraíba para ver se o método equals está funcionando
        self.g_p2 = MeuGrafo()
        self.g_p2.adiciona_vertice("J")
        self.g_p2.adiciona_vertice("C")
        self.g_p2.adiciona_vertice("E")
        self.g_p2.adiciona_vertice("P")
        self.g_p2.adiciona_vertice("M")
        self.g_p2.adiciona_vertice("T")
        self.g_p2.adiciona_vertice("Z")
        self.g_p2.adiciona_aresta('a1', 'J', 'C')
        self.g_p2.adiciona_aresta('a2', 'C', 'E')
        self.g_p2.adiciona_aresta('a3', 'C', 'E')
        self.g_p2.adiciona_aresta('a4', 'P', 'C')
        self.g_p2.adiciona_aresta('a5', 'P', 'C')
        self.g_p2.adiciona_aresta('a6', 'T', 'C')
        self.g_p2.adiciona_aresta('a7', 'M', 'C')
        self.g_p2.adiciona_aresta('a8', 'M', 'T')
        self.g_p2.adiciona_aresta('a9', 'T', 'Z')

        # Outro clone do Grafo da Paraíba para ver se o método equals está funcionando
        # Esse tem um pequena diferença na primeira aresta
        self.g_p3 = MeuGrafo()
        self.g_p3.adiciona_vertice("J")
        self.g_p3.adiciona_vertice("C")
        self.g_p3.adiciona_vertice("E")
        self.g_p3.adiciona_vertice("P")
        self.g_p3.adiciona_vertice("M")
        self.g_p3.adiciona_vertice("T")
        self.g_p3.adiciona_vertice("Z")
        self.g_p3.adiciona_aresta('a', 'J', 'C')
        self.g_p3.adiciona_aresta('a2', 'C', 'E')
        self.g_p3.adiciona_aresta('a3', 'C', 'E')
        self.g_p3.adiciona_aresta('a4', 'P', 'C')
        self.g_p3.adiciona_aresta('a5', 'P', 'C')
        self.g_p3.adiciona_aresta('a6', 'T', 'C')
        self.g_p3.adiciona_aresta('a7', 'M', 'C')
        self.g_p3.adiciona_aresta('a8', 'M', 'T')
        self.g_p3.adiciona_aresta('a9', 'T', 'Z')

        # Outro clone do Grafo da Paraíba para ver se o método equals está funcionando
        # Esse tem um pequena diferença na segunda aresta
        self.g_p4 = MeuGrafo()
        self.g_p4.adiciona_vertice("J")
        self.g_p4.adiciona_vertice("C")
        self.g_p4.adiciona_vertice("E")
        self.g_p4.adiciona_vertice("P")
        self.g_p4.adiciona_vertice("M")
        self.g_p4.adiciona_vertice("T")
        self.g_p4.adiciona_vertice("Z")
        self.g_p4.adiciona_aresta('a1', 'J', 'C')
        self.g_p4.adiciona_aresta('a2', 'J', 'E')
        self.g_p4.adiciona_aresta('a3', 'C', 'E')
        self.g_p4.adiciona_aresta('a4', 'P', 'C')
        self.g_p4.adiciona_aresta('a5', 'P', 'C')
        self.g_p4.adiciona_aresta('a6', 'T', 'C')
        self.g_p4.adiciona_aresta('a7', 'M', 'C')
        self.g_p4.adiciona_aresta('a8', 'M', 'T')
        self.g_p4.adiciona_aresta('a9', 'T', 'Z')

        # Grafo da Paraíba sem arestas paralelas
        self.g_p_sem_paralelas = MeuGrafo()
        self.g_p_sem_paralelas.adiciona_vertice("J")
        self.g_p_sem_paralelas.adiciona_vertice("C")
        self.g_p_sem_paralelas.adiciona_vertice("E")
        self.g_p_sem_paralelas.adiciona_vertice("P")
        self.g_p_sem_paralelas.adiciona_vertice("M")
        self.g_p_sem_paralelas.adiciona_vertice("T")
        self.g_p_sem_paralelas.adiciona_vertice("Z")
        self.g_p_sem_paralelas.adiciona_aresta('a1', 'J', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a2', 'C', 'E')
        self.g_p_sem_paralelas.adiciona_aresta('a3', 'P', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a4', 'T', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a5', 'M', 'C')
        self.g_p_sem_paralelas.adiciona_aresta('a6', 'M', 'T')
        self.g_p_sem_paralelas.adiciona_aresta('a7', 'T', 'Z')

        # Grafos completos
        self.g_c = MeuGrafo()
        self.g_c.adiciona_vertice("J")
        self.g_c.adiciona_vertice("C")
        self.g_c.adiciona_vertice("E")
        self.g_c.adiciona_vertice("P")
        self.g_c.adiciona_aresta('a1', 'J', 'C')
        self.g_c.adiciona_aresta('a2', 'J', 'E')
        self.g_c.adiciona_aresta('a3', 'J', 'P')
        self.g_c.adiciona_aresta('a4', 'E', 'C')
        self.g_c.adiciona_aresta('a5', 'P', 'C')
        self.g_c.adiciona_aresta('a6', 'P', 'E')

        self.g_c2 = MeuGrafo()
        self.g_c2.adiciona_vertice("Nina")
        self.g_c2.adiciona_vertice("Maria")
        self.g_c2.adiciona_aresta('amiga', 'Nina', 'Maria')

        self.g_c3 = MeuGrafo()
        self.g_c3.adiciona_vertice("Único")

        # Grafos com laco
        self.g_l1 = MeuGrafo()
        self.g_l1.adiciona_vertice("A")
        self.g_l1.adiciona_vertice("B")
        self.g_l1.adiciona_vertice("C")
        self.g_l1.adiciona_vertice("D")
        self.g_l1.adiciona_aresta('a1', 'A', 'A')
        self.g_l1.adiciona_aresta('a2', 'A', 'B')
        self.g_l1.adiciona_aresta('a3', 'A', 'A')

        self.g_l2 = MeuGrafo()
        self.g_l2.adiciona_vertice("A")
        self.g_l2.adiciona_vertice("B")
        self.g_l2.adiciona_vertice("C")
        self.g_l2.adiciona_vertice("D")
        self.g_l2.adiciona_aresta('a1', 'A', 'B')
        self.g_l2.adiciona_aresta('a2', 'B', 'B')
        self.g_l2.adiciona_aresta('a3', 'B', 'A')

        self.g_l3 = MeuGrafo()
        self.g_l3.adiciona_vertice("A")
        self.g_l3.adiciona_vertice("B")
        self.g_l3.adiciona_vertice("C")
        self.g_l3.adiciona_vertice("D")
        self.g_l3.adiciona_aresta('a1', 'C', 'A')
        self.g_l3.adiciona_aresta('a2', 'C', 'C')
        self.g_l3.adiciona_aresta('a3', 'D', 'D')
        self.g_l3.adiciona_aresta('a4', 'D', 'D')

        self.g_l4 = MeuGrafo()
        self.g_l4.adiciona_vertice("D")
        self.g_l4.adiciona_aresta('a1', 'D', 'D')

        self.g_l5 = MeuGrafo()
        self.g_l5.adiciona_vertice("C")
        self.g_l5.adiciona_vertice("D")
        self.g_l5.adiciona_aresta('a1', 'D', 'C')
        self.g_l5.adiciona_aresta('a2', 'C', 'C')

        # Grafos desconexos
        self.g_d = MeuGrafo()
        self.g_d.adiciona_vertice("A")
        self.g_d.adiciona_vertice("B")
        self.g_d.adiciona_vertice("C")
        self.g_d.adiciona_vertice("D")
        self.g_d.adiciona_aresta('asd', 'A', 'B')

        self.g_d2 = MeuGrafo()
        self.g_d2.adiciona_vertice("A")
        self.g_d2.adiciona_vertice("B")
        self.g_d2.adiciona_vertice("C")
        self.g_d2.adiciona_vertice("D")
        self.g_d2.adiciona_vertice("E")
        self.g_d2.adiciona_vertice("F")

        self.g_t1 = MeuGrafo()
        self.g_t1.adiciona_vertice("AX")
        self.g_t1.adiciona_vertice("BX")
        self.g_t1.adiciona_vertice("XA")
        self.g_t1.adiciona_vertice("XB")
        self.g_t1.adiciona_aresta("u1", "AX", "BX", 7)
        self.g_t1.adiciona_aresta("u2", "AX", "XA", 5)
        self.g_t1.adiciona_aresta("u3", "AX", "XB", 2)
        self.g_t1.adiciona_aresta("u4", "XB", "XA", 1)
        self.g_t1.adiciona_aresta("u5", "XB", "BX", 3)
        self.g_t1.adiciona_aresta("u6", "BX", "AX", 4)

        self.g_t1_mst = MeuGrafo()
        self.g_t1_mst.adiciona_vertice("AX")
        self.g_t1_mst.adiciona_vertice("XB")
        self.g_t1_mst.adiciona_vertice("XA")
        self.g_t1_mst.adiciona_vertice("BX")
        self.g_t1_mst.adiciona_aresta('u3', 'AX', 'XB', 2)
        self.g_t1_mst.adiciona_aresta('u4', 'XB', 'XA', 1)
        self.g_t1_mst.adiciona_aresta('u5', 'XB', 'BX', 3)

        self.g_t2 = MeuGrafo()
        self.g_t2.adiciona_vertice("0")
        self.g_t2.adiciona_vertice("1")
        self.g_t2.adiciona_vertice("2")
        self.g_t2.adiciona_vertice("3")
        self.g_t2.adiciona_vertice("4")
        self.g_t2.adiciona_vertice("5")
        self.g_t2.adiciona_vertice("6")
        self.g_t2.adiciona_vertice("7")
        self.g_t2.adiciona_vertice("8")
        self.g_t2.adiciona_aresta("q1", "0", "1", 4)
        self.g_t2.adiciona_aresta("q2", "0", "7", 8)
        self.g_t2.adiciona_aresta("q3", "1", "2", 8)
        self.g_t2.adiciona_aresta("q4", "1", "7", 11)
        self.g_t2.adiciona_aresta("q5", "2", "3", 7)
        self.g_t2.adiciona_aresta("q6", "2", "5", 4)
        self.g_t2.adiciona_aresta("q7", "2", "8", 2)
        self.g_t2.adiciona_aresta("q8", "3", "4", 9)
        self.g_t2.adiciona_aresta("q9", "3", "5", 14)
        self.g_t2.adiciona_aresta("q10", "4", "5", 10)
        self.g_t2.adiciona_aresta("q11", "5", "6", 2)
        self.g_t2.adiciona_aresta("q12", "6", "7", 1)
        self.g_t2.adiciona_aresta("q13", "6", "8", 6)
        self.g_t2.adiciona_aresta("q14", "7", "8", 7)

        self.g_t2_mst = MeuGrafo()
        self.g_t2_mst.adiciona_vertice("6")
        self.g_t2_mst.adiciona_vertice("7")
        self.g_t2_mst.adiciona_vertice("5")
        self.g_t2_mst.adiciona_vertice("2")
        self.g_t2_mst.adiciona_vertice("8")
        self.g_t2_mst.adiciona_vertice("3")
        self.g_t2_mst.adiciona_vertice("0")
        self.g_t2_mst.adiciona_vertice("1")
        self.g_t2_mst.adiciona_vertice("4")
        self.g_t2_mst.adiciona_aresta('q12', '6', '7', 1)
        self.g_t2_mst.adiciona_aresta('q11', '5', '6', 2)
        self.g_t2_mst.adiciona_aresta('q6', '2', '5', 4)
        self.g_t2_mst.adiciona_aresta('q7', '2', '8', 2)
        self.g_t2_mst.adiciona_aresta('q5', '2', '3', 7)
        self.g_t2_mst.adiciona_aresta('q2', '0', '7', 8)
        self.g_t2_mst.adiciona_aresta('q1', '0', '1', 4)
        self.g_t2_mst.adiciona_aresta('q8', '3', '4', 9)

        self.g_t3 = MeuGrafo()
        self.g_t3.adiciona_vertice("A")
        self.g_t3.adiciona_vertice("B")
        self.g_t3.adiciona_vertice("C")
        self.g_t3.adiciona_vertice("D")
        self.g_t3.adiciona_vertice("E")
        self.g_t3.adiciona_vertice("F")
        self.g_t3.adiciona_vertice("G")
        self.g_t3.adiciona_vertice("H")
        self.g_t3.adiciona_vertice("I")
        self.g_t3.adiciona_vertice("J")
        self.g_t3.adiciona_vertice("K")
        self.g_t3.adiciona_aresta("1", "A", "B", 10)
        self.g_t3.adiciona_aresta("2", "A", "G", 10)
        self.g_t3.adiciona_aresta("3", "A", "J", 3)
        self.g_t3.adiciona_aresta("4", "K", "G", 1)
        self.g_t3.adiciona_aresta("5", "K", "J", 6)
        self.g_t3.adiciona_aresta("6", "J", "G", 7)
        self.g_t3.adiciona_aresta("7", "J", "I", 5)
        self.g_t3.adiciona_aresta("8", "I", "G", 1)
        self.g_t3.adiciona_aresta("9", "G", "H", 1)
        self.g_t3.adiciona_aresta("10", "H", "F", 6)
        self.g_t3.adiciona_aresta("11", "F", "B", 10)
        self.g_t3.adiciona_aresta("12", "B", "G", 12)
        self.g_t3.adiciona_aresta("13", "B", "C", 2)
        self.g_t3.adiciona_aresta("14", "C", "D", 4)
        self.g_t3.adiciona_aresta("15", "D", "E", 3)
        self.g_t3.adiciona_aresta("16", "D", "B", 1)
        self.g_t3.adiciona_aresta("17", "E", "B", 1)

        self.g_t3_mst = MeuGrafo()
        self.g_t3_mst.adiciona_vertice("D")
        self.g_t3_mst.adiciona_vertice("B")
        self.g_t3_mst.adiciona_vertice("E")
        self.g_t3_mst.adiciona_vertice("K")
        self.g_t3_mst.adiciona_vertice("G")
        self.g_t3_mst.adiciona_vertice("I")
        self.g_t3_mst.adiciona_vertice("H")
        self.g_t3_mst.adiciona_vertice("C")
        self.g_t3_mst.adiciona_vertice("A")
        self.g_t3_mst.adiciona_vertice("J")
        self.g_t3_mst.adiciona_vertice("F")
        self.g_t3_mst.adiciona_aresta('16', 'D', 'B', 1)
        self.g_t3_mst.adiciona_aresta('17', 'E', 'B', 1)
        self.g_t3_mst.adiciona_aresta('4', 'K', 'G', 1)
        self.g_t3_mst.adiciona_aresta('8', 'I', 'G', 1)
        self.g_t3_mst.adiciona_aresta('9', 'G', 'H', 1)
        self.g_t3_mst.adiciona_aresta('13', 'B', 'C', 2)
        self.g_t3_mst.adiciona_aresta('3', 'A', 'J', 3)
        self.g_t3_mst.adiciona_aresta('7', 'J', 'I', 5)
        self.g_t3_mst.adiciona_aresta('10', 'H', 'F', 6)
        self.g_t3_mst.adiciona_aresta('1', 'A', 'B', 10)

        # grafos para o teste: DFS
        self.g_p_dfs1 = MeuGrafo()
        self.g_p_dfs1.adiciona_vertice("J")
        self.g_p_dfs1.adiciona_vertice("C")
        self.g_p_dfs1.adiciona_vertice("E")
        self.g_p_dfs1.adiciona_vertice("P")
        self.g_p_dfs1.adiciona_vertice("M")
        self.g_p_dfs1.adiciona_vertice("T")
        self.g_p_dfs1.adiciona_vertice("Z")
        self.g_p_dfs1.adiciona_aresta('a1', 'J', 'C')
        self.g_p_dfs1.adiciona_aresta('a2', 'C', 'E')
        self.g_p_dfs1.adiciona_aresta('a4', 'P', 'C')
        self.g_p_dfs1.adiciona_aresta('a6', 'T', 'C')
        self.g_p_dfs1.adiciona_aresta('a8', 'M', 'T')
        self.g_p_dfs1.adiciona_aresta('a9', 'T', 'Z')

        self.g_p_dfs2 = MeuGrafo()
        self.g_p_dfs2.adiciona_vertice("J")
        self.g_p_dfs2.adiciona_vertice("C")
        self.g_p_dfs2.adiciona_vertice("E")
        self.g_p_dfs2.adiciona_vertice("P")
        self.g_p_dfs2.adiciona_vertice("M")
        self.g_p_dfs2.adiciona_vertice("T")
        self.g_p_dfs2.adiciona_vertice("Z")
        self.g_p_dfs2.adiciona_aresta('a1', 'J', 'C')
        self.g_p_dfs2.adiciona_aresta('a2', 'C', 'E')
        self.g_p_dfs2.adiciona_aresta('a4', 'P', 'C')
        self.g_p_dfs2.adiciona_aresta('a6', 'T', 'C')
        self.g_p_dfs2.adiciona_aresta('a8', 'M', 'T')
        self.g_p_dfs2.adiciona_aresta('a9', 'T', 'Z')

        self.g_p_dfs3 = MeuGrafo()
        self.g_p_dfs3.adiciona_vertice("J")
        self.g_p_dfs3.adiciona_vertice("C")
        self.g_p_dfs3.adiciona_vertice("E")
        self.g_p_dfs3.adiciona_vertice("P")
        self.g_p_dfs3.adiciona_vertice("M")
        self.g_p_dfs3.adiciona_vertice("T")
        self.g_p_dfs3.adiciona_vertice("Z")
        self.g_p_dfs3.adiciona_aresta('a1', 'J', 'C')
        self.g_p_dfs3.adiciona_aresta('a2', 'C', 'E')
        self.g_p_dfs3.adiciona_aresta('a4', 'P', 'C')
        self.g_p_dfs3.adiciona_aresta('a6', 'T', 'C')
        self.g_p_dfs3.adiciona_aresta('a8', 'M', 'T')
        self.g_p_dfs3.adiciona_aresta('a9', 'T', 'Z')

        # grafos para o teste: BFS
        self.g_p_bfs1 = MeuGrafo()
        self.g_p_bfs1.adiciona_vertice("J")
        self.g_p_bfs1.adiciona_vertice("C")
        self.g_p_bfs1.adiciona_vertice("E")
        self.g_p_bfs1.adiciona_vertice("P")
        self.g_p_bfs1.adiciona_vertice("M")
        self.g_p_bfs1.adiciona_vertice("T")
        self.g_p_bfs1.adiciona_vertice("Z")
        self.g_p_bfs1.adiciona_aresta('a1', 'J', 'C')
        self.g_p_bfs1.adiciona_aresta('a2', 'C', 'E')
        self.g_p_bfs1.adiciona_aresta('a4', 'P', 'C')
        self.g_p_bfs1.adiciona_aresta('a6', 'T', 'C')
        self.g_p_bfs1.adiciona_aresta('a7', 'M', 'C')
        self.g_p_bfs1.adiciona_aresta('a9', 'T', 'Z')

        self.g_p_bfs2 = MeuGrafo()
        self.g_p_bfs2.adiciona_vertice("J")
        self.g_p_bfs2.adiciona_vertice("C")
        self.g_p_bfs2.adiciona_vertice("E")
        self.g_p_bfs2.adiciona_vertice("P")
        self.g_p_bfs2.adiciona_vertice("M")
        self.g_p_bfs2.adiciona_vertice("T")
        self.g_p_bfs2.adiciona_vertice("Z")
        self.g_p_bfs2.adiciona_aresta('a1', 'J', 'C')
        self.g_p_bfs2.adiciona_aresta('a2', 'C', 'E')
        self.g_p_bfs2.adiciona_aresta('a4', 'P', 'C')
        self.g_p_bfs2.adiciona_aresta('a6', 'T', 'C')
        self.g_p_bfs2.adiciona_aresta('a7', 'M', 'C')
        self.g_p_bfs2.adiciona_aresta('a9', 'T', 'Z')

        self.g_p_bfs3 = MeuGrafo()
        self.g_p_bfs3.adiciona_vertice("J")
        self.g_p_bfs3.adiciona_vertice("C")
        self.g_p_bfs3.adiciona_vertice("E")
        self.g_p_bfs3.adiciona_vertice("P")
        self.g_p_bfs3.adiciona_vertice("M")
        self.g_p_bfs3.adiciona_vertice("T")
        self.g_p_bfs3.adiciona_vertice("Z")
        self.g_p_bfs3.adiciona_aresta('a1', 'J', 'C')
        self.g_p_bfs3.adiciona_aresta('a2', 'C', 'E')
        self.g_p_bfs3.adiciona_aresta('a4', 'P', 'C')
        self.g_p_bfs3.adiciona_aresta('a6', 'T', 'C')
        self.g_p_bfs3.adiciona_aresta('a7', 'M', 'C')
        self.g_p_bfs3.adiciona_aresta('a9', 'T', 'Z')


    def test_adiciona_aresta(self):
        self.assertTrue(self.g_p.adiciona_aresta('a10', 'J', 'C'))
        a = Aresta("zxc", self.g_p.get_vertice("C"), self.g_p.get_vertice("Z"))
        self.assertTrue(self.g_p.adiciona_aresta(a))
        with self.assertRaises(ArestaInvalidaError):
            self.assertTrue(self.g_p.adiciona_aresta(a))
        with self.assertRaises(VerticeInvalidoError):
            self.assertTrue(self.g_p.adiciona_aresta('b1', '', 'C'))
        with self.assertRaises(VerticeInvalidoError):
            self.assertTrue(self.g_p.adiciona_aresta('b1', 'A', 'C'))
        with self.assertRaises(NotImplementedError):
            self.g_p.adiciona_aresta('')
        with self.assertRaises(NotImplementedError):
            self.g_p.adiciona_aresta('aa-bb')
        with self.assertRaises(VerticeInvalidoError):
            self.g_p.adiciona_aresta('x', 'J', 'V')
        with self.assertRaises(ArestaInvalidaError):
            self.g_p.adiciona_aresta('a1', 'J', 'C')

    def test_eq(self):
        self.assertEqual(self.g_p, self.g_p2)
        self.assertNotEqual(self.g_p, self.g_p3)
        self.assertNotEqual(self.g_p, self.g_p_sem_paralelas)
        self.assertNotEqual(self.g_p, self.g_p4)

    def test_vertices_nao_adjacentes(self):
        self.assertEqual(self.g_p.vertices_nao_adjacentes(),
                         {'J-E', 'J-P', 'J-M', 'J-T', 'J-Z', 'C-Z', 'E-P', 'E-M', 'E-T', 'E-Z', 'P-M', 'P-T', 'P-Z',
                          'M-Z'})
        self.assertEqual(self.g_c.vertices_nao_adjacentes(), set())
        self.assertEqual(self.g_c3.vertices_nao_adjacentes(), set())

    def test_ha_laco(self):
        self.assertFalse(self.g_p.ha_laco())
        self.assertFalse(self.g_p2.ha_laco())
        self.assertFalse(self.g_p3.ha_laco())
        self.assertFalse(self.g_p4.ha_laco())
        self.assertFalse(self.g_p_sem_paralelas.ha_laco())
        self.assertFalse(self.g_d.ha_laco())
        self.assertFalse(self.g_c.ha_laco())
        self.assertFalse(self.g_c2.ha_laco())
        self.assertFalse(self.g_c3.ha_laco())
        self.assertTrue(self.g_l1.ha_laco())
        self.assertTrue(self.g_l2.ha_laco())
        self.assertTrue(self.g_l3.ha_laco())
        self.assertTrue(self.g_l4.ha_laco())
        self.assertTrue(self.g_l5.ha_laco())

    def test_grau(self):
        # Paraíba
        self.assertEqual(self.g_p.grau('J'), 1)
        self.assertEqual(self.g_p.grau('C'), 7)
        self.assertEqual(self.g_p.grau('E'), 2)
        self.assertEqual(self.g_p.grau('P'), 2)
        self.assertEqual(self.g_p.grau('M'), 2)
        self.assertEqual(self.g_p.grau('T'), 3)
        self.assertEqual(self.g_p.grau('Z'), 1)
        with self.assertRaises(VerticeInvalidoError):
            self.assertEqual(self.g_p.grau('G'), 5)

        self.assertEqual(self.g_d.grau('A'), 1)
        self.assertEqual(self.g_d.grau('C'), 0)
        self.assertNotEqual(self.g_d.grau('D'), 2)
        self.assertEqual(self.g_d2.grau('A'), 0)

        # Completos
        self.assertEqual(self.g_c.grau('J'), 3)
        self.assertEqual(self.g_c.grau('C'), 3)
        self.assertEqual(self.g_c.grau('E'), 3)
        self.assertEqual(self.g_c.grau('P'), 3)

        # Com laço. Lembrando que cada laço conta 2 vezes por vértice para cálculo do grau
        self.assertEqual(self.g_l1.grau('A'), 5)
        self.assertEqual(self.g_l2.grau('B'), 4)
        self.assertEqual(self.g_l4.grau('D'), 2)

    def test_ha_paralelas(self):
        self.assertTrue(self.g_p.ha_paralelas())
        self.assertFalse(self.g_p_sem_paralelas.ha_paralelas())
        self.assertFalse(self.g_c.ha_paralelas())
        self.assertFalse(self.g_c2.ha_paralelas())
        self.assertFalse(self.g_c3.ha_paralelas())
        self.assertTrue(self.g_l1.ha_paralelas())

    def test_arestas_sobre_vertice(self):
        self.assertEqual(self.g_p.arestas_sobre_vertice('J'), {'a1'})
        self.assertEqual(self.g_p.arestas_sobre_vertice('C'), {'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7'})
        self.assertEqual(self.g_p.arestas_sobre_vertice('M'), {'a7', 'a8'})
        self.assertEqual(self.g_l2.arestas_sobre_vertice('B'), {'a1', 'a2', 'a3'})
        self.assertEqual(self.g_d.arestas_sobre_vertice('C'), set())
        self.assertEqual(self.g_d.arestas_sobre_vertice('A'), {'asd'})
        with self.assertRaises(VerticeInvalidoError):
            self.g_p.arestas_sobre_vertice('A')

    def test_eh_completo(self):
        self.assertFalse(self.g_p.eh_completo())
        self.assertFalse((self.g_p_sem_paralelas.eh_completo()))
        self.assertTrue((self.g_c.eh_completo()))
        self.assertTrue((self.g_c2.eh_completo()))
        self.assertTrue((self.g_c3.eh_completo()))
        self.assertFalse((self.g_l1.eh_completo()))
        self.assertFalse((self.g_l2.eh_completo()))
        self.assertFalse((self.g_l3.eh_completo()))
        self.assertFalse((self.g_l4.eh_completo()))
        self.assertFalse((self.g_l5.eh_completo()))
        self.assertFalse((self.g_d.eh_completo()))
        self.assertFalse((self.g_d2.eh_completo()))

    def test_dfs(self):
        self.assertEqual(self.g_p.dfs('J'), self.g_p_dfs1)
        self.assertEqual(self.g_p.dfs('C'), self.g_p_dfs2)
        self.assertEqual(self.g_p.dfs('E'), self.g_p_dfs3)

    def test_bfs(self):
        self.assertEqual(self.g_p.bfs('J'), self.g_p_bfs1)
        self.assertEqual(self.g_p.bfs('C'), self.g_p_bfs2)
        self.assertEqual(self.g_p.bfs('E'), self.g_p_bfs3)

    def teste_caminho(self):
        self.assertNotEqual(self.g_p.caminho(2), ['J', 'a1', 'C', 'a6', 'T', 'a8', 'M'])
        self.assertNotEqual(self.g_p.caminho(3), ['J', 'a1', 'C', 'a2', 'E'])
        self.assertFalse(self.g_p.caminho(30))

    def test_ha_ciclo(self):
        self.assertTrue(self.g_p.ha_ciclo())
        self.assertTrue(self.g_l3.ha_ciclo())
        self.assertFalse(self.g_d2.ha_ciclo())

    def test_conexo(self):
        self.assertTrue(self.g_p.conexo())
        self.g_p.adiciona_vertice('S')

        vazio = MeuGrafo()
        self.assertFalse(vazio.conexo())
    def test_Prim(self):
        self.assertEqual(self.g_t1.prim(), self.g_t1_mst)
        self.assertEqual(self.g_t2.prim(), self.g_t2_mst)
        self.assertEqual(self.g_t3.prim(), self.g_t3_mst)

    def test_Prim_modificado(self):
        self.assertEqual(self.g_t1.prim_modificado(), self.g_t1_mst)
        self.assertEqual(self.g_t2.prim_modificado(), self.g_t2_mst)

    def test_kruskall(self):
        self.assertEqual(self.g_t1.kruskall(), self.g_t1_mst)
        self.assertEqual(self.g_t2.kruskall(), self.g_t2_mst)
        self.assertEqual(self.g_t3.kruskall(), self.g_t3_mst)

    def test_kruskall_modificado(self):
        self.assertEqual(self.g_t1.kruskall_modificado(), self.g_t1_mst)
        self.assertEqual(self.g_t2.kruskall_modificado(), self.g_t2_mst)
